### ISSUE TITLE
Had an issue with start this demo app

### ISSUE THREAD

**Issue by stojankukrika** [cometchat-pro-samples/ionic-chat-app#8]
When I use `npm install --force` it to install node packages. But when I run `ionic serve` I get a loot of errors:
`[INFO] Browser window opened to http://localhost:8100!

[ng] ℹ ｢wdm｣: wait until bundle finished: /
[ng] Date: 2022-08-12T06:57:58.516Z
[ng] Hash: 0c62fbde1f0402fb46f9
[ng] Time: 6146ms
[ng] 
[ng] ERROR in ./src/global.scss (./node_modules/@angular-devkit/build-angular/src/angular-cli-files/plugins/raw-css-loader.js!./node_modules/postcss-loader/src??embedded!./node_modules/sass-loader/lib/loader.js??ref--14-3!./src/global.scss)
[ng] Module build failed (from ./node_modules/sass-loader/lib/loader.js):
[ng] Error: Cannot find module 'node-sass'
[ng] Require stack:
[ng] - /Users/stojan/development/cordova-ionic-chat-app/node_modules/sass-loader/lib/loader.js
[ng] - /Users/stojan/development/cordova-ionic-chat-app/node_modules/loader-runner/lib/loadLoader.js
[ng] - /Users/stojan/development/cordova-ionic-chat-app/node_modules/loader-runner/lib/LoaderRunner.js
[ng] - /Users/stojan/development/cordova-ionic-chat-app/node_modules/webpack/lib/NormalModule.js
[ng] - /Users/stojan/development/cordova-ionic-chat-app/node_modules/webpack/lib/NormalModuleFactory.js
[ng] - /Users/stojan/development/cordova-ionic-chat-app/node_modules/webpack/lib/Compiler.js
[ng] - /Users/stojan/development/cordova-ionic-chat-app/node_modules/webpack/lib/webpack.js
[ng] - /Users/stojan/development/cordova-ionic-chat-app/node_modules/@angular-devkit/build-webpack/src/webpack/index.js
[ng] - /Users/stojan/development/cordova-ionic-chat-app/node_modules/@angular-devkit/build-webpack/src/index.js
[ng] - /Users/stojan/development/cordova-ionic-chat-app/node_modules/@angular-devkit/build-angular/src/dev-server/index.js
[ng] - /Users/stojan/development/cordova-ionic-chat-app/node_modules/@angular/cli/node_modules/@angular-devkit/architect/src/architect-legacy.js
[ng] - /Users/stojan/development/cordova-ionic-chat-app/node_modules/@angular/cli/node_modules/@angular-devkit/architect/src/index.js
[ng] - /Users/stojan/development/cordova-ionic-chat-app/node_modules/@angular/cli/models/architect-command.js
[ng] - /Users/stojan/development/cordova-ionic-chat-app/node_modules/@angular/cli/commands/build-impl.js
[ng] - /Users/stojan/development/cordova-ionic-chat-app/node_modules/@angular/cli/node_modules/@angular-devkit/schematics/tools/export-ref.js
[ng] - /Users/stojan/development/cordova-ionic-chat-app/node_modules/@angular/cli/node_modules/@angular-devkit/schematics/tools/index.js
[ng] - /Users/stojan/development/cordova-ionic-chat-app/node_modules/@angular/cli/utilities/json-schema.js
[ng] - /Users/stojan/development/cordova-ionic-chat-app/node_modules/@angular/cli/models/command-runner.js
[ng] - /Users/stojan/development/cordova-ionic-chat-app/node_modules/@angular/cli/lib/cli/index.js
[ng] - /Users/stojan/development/cordova-ionic-chat-app/node_modules/@angular/cli/lib/init.js
[ng] - /Users/stojan/development/cordova-ionic-chat-app/node_modules/@angular/cli/bin/ng
[ng]     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
[ng]     at Function.Module._load (node:internal/modules/cjs/loader:778:27)
[ng]     at Module.require (node:internal/modules/cjs/loader:1005:19)
[ng]     at require (node:internal/modules/cjs/helpers:102:18)
[ng]     at Object.sassLoader (/Users/stojan/development/cordova-ionic-chat-app/node_modules/sass-loader/lib/loader.js:46:72)
[ng] ERROR in ./src/theme/variables.scss (./node_modules/@angular-devkit/build-angular/src/angular-cli-files/plugins/raw-css-loader.js!./node_modules/postcss-loader/src??embedded!./node_modules/sass-loader/lib/loader.js??ref--14-3!./src/theme/variables.scss)
[ng] Module build failed (from ./node_modules/sass-loader/lib/loader.js):
[ng] Error: Cannot find module 'node-sass'
[ng] Require stack:
[ng] - /Users/stojan/development/cordova-ionic-chat-app/node_modules/sass-loader/lib/loader.js
[ng] - /Users/stojan/development/cordova-ionic-chat-app/node_modules/loader-runner/lib/loadLoader.js
[ng] - /Users/stojan/development/cordova-ionic-chat-app/node_modules/loader-runner/lib/LoaderRunner.js
[ng] - /Users/stojan/development/cordova-ionic-chat-app/node_modules/webpack/lib/NormalModule.js
[ng] - /Users/stojan/development/cordova-ionic-chat-app/node_modules/webpack/lib/NormalModuleFactory.js
[ng] - /Users/stojan/development/cordova-ionic-chat-app/node_modules/webpack/lib/Compiler.js
[ng] - /Users/stojan/development/cordova-ionic-chat-app/node_modules/webpack/lib/webpack.js
[ng] - /Users/stojan/development/cordova-ionic-chat-app/node_modules/@angular-devkit/build-webpack/src/webpack/index.js
[ng] - /Users/stojan/development/cordova-ionic-chat-app/node_modules/@angular-devkit/build-webpack/src/index.js
[ng] - /Users/stojan/development/cordova-ionic-chat-app/node_modules/@angular-devkit/build-angular/src/dev-server/index.js
[ng] - /Users/stojan/development/cordova-ionic-chat-app/node_modules/@angular/cli/node_modules/@angular-devkit/architect/src/architect-legacy.js
[ng] - /Users/stojan/development/cordova-ionic-chat-app/node_modules/@angular/cli/node_modules/@angular-devkit/architect/src/index.js
[ng] - /Users/stojan/development/cordova-ionic-chat-app/node_modules/@angular/cli/models/architect-command.js
[ng] - /Users/stojan/development/cordova-ionic-chat-app/node_modules/@angular/cli/commands/build-impl.js
[ng] - /Users/stojan/development/cordova-ionic-chat-app/node_modules/@angular/cli/node_modules/@angular-devkit/schematics/tools/export-ref.js
[ng] - /Users/stojan/development/cordova-ionic-chat-app/node_modules/@angular/cli/node_modules/@angular-devkit/schematics/tools/index.js
[ng] - /Users/stojan/development/cordova-ionic-chat-app/node_modules/@angular/cli/utilities/json-schema.js
[ng] - /Users/stojan/development/cordova-ionic-chat-app/node_modules/@angular/cli/models/command-runner.js
[ng] - /Users/stojan/development/cordova-ionic-chat-app/node_modules/@angular/cli/lib/cli/index.js
[ng] - /Users/stojan/development/cordova-ionic-chat-app/node_modules/@angular/cli/lib/init.js
[ng] - /Users/stojan/development/cordova-ionic-chat-app/node_modules/@angular/cli/bin/ng
[ng]     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
[ng]     at Function.Module._load (node:internal/modules/cjs/loader:778:27)
[ng]     at Module.require (node:internal/modules/cjs/loader:1005:19)
[ng]     at require (node:internal/modules/cjs/helpers:102:18)
[ng]     at Object.sassLoader (/Users/stojan/development/cordova-ionic-chat-app/node_modules/sass-loader/lib/loader.js:46:72)
[ng] ERROR in ./src/app/component/image-viewer/image-viewer.component.scss
[ng] Module build failed (from ./node_modules/sass-loader/lib/loader.js):
[ng] Error: Cannot find module 'node-sass'
[ng] Require stack:
[ng] - /Users/stojan/development/cordova-ionic-chat-app/node_modules/sass-loader/lib/loader.js
[ng] - /Users/stojan/development/cordova-ionic-chat-app/node_modules/loader-runner/lib/loadLoader.js
[ng] - /Users/stojan/development/cordova-ionic-chat-app/node_modules/loader-runner/lib/LoaderRunner.js
[ng] - /Users/stojan/development/cordova-ionic-chat-app/node_modules/webpack/lib/NormalModule.js
[ng] - /Users/stojan/development/cordova-ionic-chat-app/node_modules/webpack/lib/NormalModuleFactory.js
[ng] - /Users/stojan/development/cordova-ionic-chat-app/node_modules/webpack/lib/Compiler.js
[ng] - /Users/stojan/development/cordova-ionic-chat-app/node_modules/webpack/lib/webpack.js
[ng] - /Users/stojan/development/cordova-ionic-chat-app/node_modules/@angular-devkit/build-webpack/src/webpack/index.js
[ng] - /Users/stojan/development/cordova-ionic-chat-app/node_modules/@angular-devkit/build-webpack/src/index.js
[ng] - /Users/stojan/development/cordova-ionic-chat-app/node_modules/@angular-devkit/build-angular/src/dev-server/index.js
[ng] - /Users/stojan/development/cordova-ionic-chat-app/node_modules/@angular/cli/node_modules/@angular-devkit/architect/src/architect-legacy.js
[ng] - /Users/stojan/development/cordova-ionic-chat-app/node_modules/@angular/cli/node_modules/@angular-devkit/architect/src/index.js
[ng] - /Users/stojan/development/cordova-ionic-chat-app/node_modules/@angular/cli/models/architect-command.js
[ng] - /Users/stojan/development/cordova-ionic-chat-app/node_modules/@angular/cli/commands/build-impl.js
[ng] - /Users/stojan/development/cordova-ionic-chat-app/node_modules/@angular/cli/node_modules/@angular-devkit/schematics/tools/export-ref.js
[ng] - /Users/stojan/development/cordova-ionic-chat-app/node_modules/@angular/cli/node_modules/@angular-devkit/schematics/tools/index.js
[ng] chunk {blocked-users-blocked-users-module} blocked-users-blocked-users-module.js, blocked-users-blocked-users-module.js.map (blocked-users-blocked-users-module) 13.2 kB  [rendered]
[ng] chunk {chat-view-chat-view-module} chat-view-chat-view-module.js, chat-view-chat-view-module.js.map (chat-view-chat-view-module) 29.8 kB  [rendered]
[ng] chunk {common} common.js, common.js.map (common) 14.7 kB  [rendered]
[ng] chunk {es2015-polyfills} es2015-polyfills.js, es2015-polyfills.js.map (es2015-polyfills) 285 kB [initial] [rendered]
[ng] chunk {groupchat-view-groupchat-view-module} groupchat-view-groupchat-view-module.js, groupchat-view-groupchat-view-module.js.map (groupchat-view-groupchat-view-module) 30.2 kB  [rendered]
[ng] chunk {login-login-module} login-login-module.js, login-login-module.js.map (login-login-module) 12.4 kB  [rendered]
[ng] chunk {main} main.js, main.js.map (main) 36.8 kB [initial] [rendered]
[ng] chunk {pages-tabs-tabs-module} pages-tabs-tabs-module.js, pages-tabs-tabs-module.js.map (pages-tabs-tabs-module) 5.87 kB  [rendered]
[ng] chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 237 kB [initial] [rendered]
[ng] chunk {runtime} runtime.js, runtime.js.map (runtime) 9.12 kB [entry] [rendered]
[ng] chunk {styles} styles.js, styles.js.map (styles) 23.9 kB [initial] [rendered]
[ng] chunk {tab1-tab1-module} tab1-tab1-module.js, tab1-tab1-module.js.map (tab1-tab1-module) 19.5 kB  [rendered]
[ng] chunk {tab2-tab2-module} tab2-tab2-module.js, tab2-tab2-module.js.map (tab2-tab2-module) 14.8 kB  [rendered]
[ng] chunk {vendor} vendor.js, vendor.js.map (vendor) 5.23 MB [initial] [rendered]
[ng] ℹ ｢wdm｣: Failed to compile.
[ng] - /Users/stojan/development/cordova-ionic-chat-app/node_modules/@angular/cli/utilities/json-schema.js
[ng] - /Users/stojan/development/cordova-ionic-chat-app/node_modules/@angular/cli/models/command-runner.js
[ng] - /Users/stojan/development/cordova-ionic-chat-app/node_modules/@angular/cli/lib/cli/index.js
[ng] - /Users/stojan/development/cordova-ionic-chat-app/node_modules/@angular/cli/lib/init.js
[ng] - /Users/stojan/development/cordova-ionic-chat-app/node_modules/@angular/cli/bin/ng
[ng]     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
[ng]     at Function.Module._load (node:internal/modules/cjs/loader:778:27)
[ng]     at Module.require (node:internal/modules/cjs/loader:1005:19)
[ng]     at require (node:internal/modules/cjs/helpers:102:18)
[ng]     at Object.sassLoader (/Users/stojan/development/cordova-ionic-chat-app/node_modules/sass-loader/lib/loader.js:46:72)
[ng] ERROR in ./src/app/login/login.page.scss
[ng] Module build failed (from ./node_modules/sass-loader/lib/loader.js):
[ng] Error: Cannot find module 'node-sass'
[ng] Require stack:
[ng] - /Users/stojan/development/cordova-ionic-chat-app/node_modules/sass-loader/lib/loader.js
[ng] - /Users/stojan/development/cordova-ionic-chat-app/node_modules/loader-runner/lib/loadLoader.js
[ng] - /Users/stojan/development/cordova-ionic-chat-app/node_modules/loader-runner/lib/LoaderRunner.js
[ng] - /Users/stojan/development/cordova-ionic-chat-app/node_modules/webpack/lib/NormalModule.js
[ng] - /Users/stojan/development/cordova-ionic-chat-app/node_modules/webpack/lib/NormalModuleFactory.js
[ng] - /Users/stojan/development/cordova-ionic-chat-app/node_modules/webpack/lib/Compiler.js
[ng] - /Users/stojan/development/cordova-ionic-chat-app/node_modules/webpack/lib/webpack.js
[ng] - /Users/stojan/development/cordova-ionic-chat-app/node_modules/@angular-devkit/build-webpack/src/webpack/index.js
[ng] - /Users/stojan/development/cordova-ionic-chat-app/node_modules/@angular-devkit/build-webpack/src/index.js
[ng] - /Users/stojan/development/cordova-ionic-chat-app/node_modules/@angular-devkit/build-angular/src/dev-server/index.js
[ng] - /Users/stojan/development/cordova-ionic-chat-app/node_modules/@angular/cli/node_modules/@angular-devkit/architect/src/architect-legacy.js
[ng] - /Users/stojan/development/cordova-ionic-chat-app/node_modules/@angular/cli/node_modules/@angular-devkit/architect/src/index.js
[ng] - /Users/stojan/development/cordova-ionic-chat-app/node_modules/@angular/cli/models/architect-command.js
[ng] - /Users/stojan/development/cordova-ionic-chat-app/node_modules/@angular/cli/commands/build-impl.js
[ng] - /Users/stojan/development/cordova-ionic-chat-app/node_modules/@angular/cli/node_modules/@angular-devkit/schematics/tools/export-ref.js
[ng] - /Users/stojan/development/cordova-ionic-chat-app/node_modules/@angular/cli/node_modules/@angular-devkit/schematics/tools/index.js
[ng] - /Users/stojan/development/cordova-ionic-chat-app/node_modules/@angular/cli/utilities/json-schema.js
[ng] - /Users/stojan/development/cordova-ionic-chat-app/node_modules/@angular/cli/models/command-runner.js
[ng] - /Users/stojan/development/cordova-ionic-chat-app/node_modules/@angular/cli/lib/cli/index.js
[ng] - /Users/stojan/development/cordova-ionic-chat-app/node_modules/@angular/cli/lib/init.js
[ng] - /Users/stojan/development/cordova-ionic-chat-app/node_modules/@angular/cli/bin/ng
[ng]     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
[ng]     at Function.Module._load (node:internal/modules/cjs/loader:778:27)
[ng]     at Module.require (node:internal/modules/cjs/loader:1005:19)
[ng]     at require (node:internal/modules/cjs/helpers:102:18)
[ng]     at Object.sassLoader (/Users/stojan/development/cordova-ionic-chat-app/node_modules/sass-loader/lib/loader.js:46:72)
[ng] ERROR in ./src/app/pages/tab1/tab1.page.scss
[ng] Module build failed (from ./node_modules/sass-loader/lib/loader.js):
[ng] Error: Cannot find module 'node-sass'
[ng] Require stack:
[ng] - /Users/stojan/development/cordova-ionic-chat-app/node_modules/sass-loader/lib/loader.js
[ng] - /Users/stojan/development/cordova-ionic-chat-app/node_modules/loader-runner/lib/loadLoader.js
[ng] - /Users/stojan/development/cordova-ionic-chat-app/node_modules/loader-runner/lib/LoaderRunner.js
[ng] - /Users/stojan/development/cordova-ionic-chat-app/node_modules/webpack/lib/NormalModule.js
[ng] - /Users/stojan/development/cordova-ionic-chat-app/node_modules/webpack/lib/NormalModuleFactory.js
[ng] - /Users/stojan/development/cordova-ionic-chat-app/node_modules/webpack/lib/Compiler.js
[ng] - /Users/stojan/development/cordova-ionic-chat-app/node_modules/webpack/lib/webpack.js
[ng] - /Users/stojan/development/cordova-ionic-chat-app/node_modules/@angular-devkit/build-webpack/src/webpack/index.js
[ng] - /Users/stojan/development/cordova-ionic-chat-app/node_modules/@angular-devkit/build-webpack/src/index.js
[ng] - /Users/stojan/development/cordova-ionic-chat-app/node_modules/@angular-devkit/build-angular/src/dev-server/index.js
[ng] - /Users/stojan/development/cordova-ionic-chat-app/node_modules/@angular/cli/node_modules/@angular-devkit/architect/src/architect-legacy.js
[ng] - /Users/stojan/development/cordova-ionic-chat-app/node_modules/@angular/cli/node_modules/@angular-devkit/architect/src/index.js
[ng] - /Users/stojan/development/cordova-ionic-chat-app/node_modules/@angular/cli/models/architect-command.js
[ng] - /Users/stojan/development/cordova-ionic-chat-app/node_modules/@angular/cli/commands/build-impl.js
[ng] - /Users/stojan/development/cordova-ionic-chat-app/node_modules/@angular/cli/node_modules/@angular-devkit/schematics/tools/export-ref.js
[ng] - /Users/stojan/development/cordova-ionic-chat-app/node_modules/@angular/cli/node_modules/@angular-devkit/schematics/tools/index.js
[ng] - /Users/stojan/development/cordova-ionic-chat-app/node_modules/@angular/cli/utilities/json-schema.js
[ng] - /Users/stojan/development/cordova-ionic-chat-app/node_modules/@angular/cli/models/command-runner.js
[ng] - /Users/stojan/development/cordova-ionic-chat-app/node_modules/@angular/cli/lib/cli/index.js
[ng] - /Users/stojan/development/cordova-ionic-chat-app/node_modules/@angular/cli/lib/init.js
[ng] - /Users/stojan/development/cordova-ionic-chat-app/node_modules/@angular/cli/bin/ng
[ng]     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
[ng]     at Function.Module._load (node:internal/modules/cjs/loader:778:27)
[ng]     at Module.require (node:internal/modules/cjs/loader:1005:19)
[ng]     at require (node:internal/modules/cjs/helpers:102:18)
[ng]     at Object.sassLoader (/Users/stojan/development/cordova-ionic-chat-app/node_modules/sass-loader/lib/loader.js:46:72)
[ng] ERROR in ./src/app/blocked-users/blocked-users.page.scss
[ng] Module build failed (from ./node_modules/sass-loader/lib/loader.js):
[ng] Error: Cannot find module 'node-sass'
[ng] Require stack:
[ng] - /Users/stojan/development/cordova-ionic-chat-app/node_modules/sass-loader/lib/loader.js
[ng] - /Users/stojan/development/cordova-ionic-chat-app/node_modules/loader-runner/lib/loadLoader.js
[ng] - /Users/stojan/development/cordova-ionic-chat-app/node_modules/loader-runner/lib/LoaderRunner.js
[ng] - /Users/stojan/development/cordova-ionic-chat-app/node_modules/webpack/lib/NormalModule.js
[ng] - /Users/stojan/development/cordova-ionic-chat-app/node_modules/webpack/lib/NormalModuleFactory.js
[ng] - /Users/stojan/development/cordova-ionic-chat-app/node_modules/webpack/lib/Compiler.js
[ng] - /Users/stojan/development/cordova-ionic-chat-app/node_modules/webpack/lib/webpack.js
[ng] - /Users/stojan/development/cordova-ionic-chat-app/node_modules/@angular-devkit/build-webpack/src/webpack/index.js
[ng] - /Users/stojan/development/cordova-ionic-chat-app/node_modules/@angular-devkit/build-webpack/src/index.js
[ng] - /Users/stojan/development/cordova-ionic-chat-app/node_modules/@angular-devkit/build-angular/src/dev-server/index.js
[ng] - /Users/stojan/development/cordova-ionic-chat-app/node_modules/@angular/cli/node_modules/@angular-devkit/architect/src/architect-legacy.js
[ng] - /Users/stojan/development/cordova-ionic-chat-app/node_modules/@angular/cli/node_modules/@angular-devkit/architect/src/index.js
[ng] - /Users/stojan/development/cordova-ionic-chat-app/node_modules/@angular/cli/models/architect-command.js
[ng] - /Users/stojan/development/cordova-ionic-chat-app/node_modules/@angular/cli/commands/build-impl.js
[ng] - /Users/stojan/development/cordova-ionic-chat-app/node_modules/@angular/cli/node_modules/@angular-devkit/schematics/tools/export-ref.js
[ng] - /Users/stojan/development/cordova-ionic-chat-app/node_modules/@angular/cli/node_modules/@angular-devkit/schematics/tools/index.js
[ng] - /Users/stojan/development/cordova-ionic-chat-app/node_modules/@angular/cli/utilities/json-schema.js
[ng] - /Users/stojan/development/cordova-ionic-chat-app/node_modules/@angular/cli/models/command-runner.js
[ng] - /Users/stojan/development/cordova-ionic-chat-app/node_modules/@angular/cli/lib/cli/index.js
[ng] - /Users/stojan/development/cordova-ionic-chat-app/node_modules/@angular/cli/lib/init.js
[ng] - /Users/stojan/development/cordova-ionic-chat-app/node_modules/@angular/cli/bin/ng
[ng]     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
[ng]     at Function.Module._load (node:internal/modules/cjs/loader:778:27)
[ng]     at Module.require (node:internal/modules/cjs/loader:1005:19)
[ng]     at require (node:internal/modules/cjs/helpers:102:18)
[ng]     at Object.sassLoader (/Users/stojan/development/cordova-ionic-chat-app/node_modules/sass-loader/lib/loader.js:46:72)
[ng] ERROR in ./src/app/chat-view/chat-view.page.scss
[ng] Module build failed (from ./node_modules/sass-loader/lib/loader.js):
[ng] Error: Cannot find module 'node-sass'
[ng] Require stack:
[ng] - /Users/stojan/development/cordova-ionic-chat-app/node_modules/sass-loader/lib/loader.js
[ng] - /Users/stojan/development/cordova-ionic-chat-app/node_modules/loader-runner/lib/loadLoader.js
[ng] - /Users/stojan/development/cordova-ionic-chat-app/node_modules/loader-runner/lib/LoaderRunner.js
[ng] - /Users/stojan/development/cordova-ionic-chat-app/node_modules/webpack/lib/NormalModule.js
[ng] - /Users/stojan/development/cordova-ionic-chat-app/node_modules/webpack/lib/NormalModuleFactory.js
[ng] - /Users/stojan/development/cordova-ionic-chat-app/node_modules/webpack/lib/Compiler.js
[ng] - /Users/stojan/development/cordova-ionic-chat-app/node_modules/webpack/lib/webpack.js
[ng] - /Users/stojan/development/cordova-ionic-chat-app/node_modules/@angular-devkit/build-webpack/src/webpack/index.js
[ng] - /Users/stojan/development/cordova-ionic-chat-app/node_modules/@angular-devkit/build-webpack/src/index.js
[ng] - /Users/stojan/development/cordova-ionic-chat-app/node_modules/@angular-devkit/build-angular/src/dev-server/index.js
[ng] - /Users/stojan/development/cordova-ionic-chat-app/node_modules/@angular/cli/node_modules/@angular-devkit/architect/src/architect-legacy.js
[ng] - /Users/stojan/development/cordova-ionic-chat-app/node_modules/@angular/cli/node_modules/@angular-devkit/architect/src/index.js
[ng] - /Users/stojan/development/cordova-ionic-chat-app/node_modules/@angular/cli/models/architect-command.js
[ng] - /Users/stojan/development/cordova-ionic-chat-app/node_modules/@angular/cli/commands/build-impl.js
[ng] - /Users/stojan/development/cordova-ionic-chat-app/node_modules/@angular/cli/node_modules/@angular-devkit/schematics/tools/export-ref.js
[ng] - /Users/stojan/development/cordova-ionic-chat-app/node_modules/@angular/cli/node_modules/@angular-devkit/schematics/tools/index.js
[ng] - /Users/stojan/development/cordova-ionic-chat-app/node_modules/@angular/cli/utilities/json-schema.js
[ng] - /Users/stojan/development/cordova-ionic-chat-app/node_modules/@angular/cli/models/command-runner.js
[ng] - /Users/stojan/development/cordova-ionic-chat-app/node_modules/@angular/cli/lib/cli/index.js
[ng] - /Users/stojan/development/cordova-ionic-chat-app/node_modules/@angular/cli/lib/init.js
[ng] - /Users/stojan/development/cordova-ionic-chat-app/node_modules/@angular/cli/bin/ng
[ng]     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
[ng]     at Function.Module._load (node:internal/modules/cjs/loader:778:27)
[ng]     at Module.require (node:internal/modules/cjs/loader:1005:19)
[ng]     at require (node:internal/modules/cjs/helpers:102:18)
[ng]     at Object.sassLoader (/Users/stojan/development/cordova-ionic-chat-app/node_modules/sass-loader/lib/loader.js:46:72)
[ng] ERROR in ./src/app/pages/tab2/tab2.page.scss
[ng] Module build failed (from ./node_modules/sass-loader/lib/loader.js):
[ng] Error: Cannot find module 'node-sass'
[ng] Require stack:
[ng] - /Users/stojan/development/cordova-ionic-chat-app/node_modules/sass-loader/lib/loader.js
[ng] - /Users/stojan/development/cordova-ionic-chat-app/node_modules/loader-runner/lib/loadLoader.js
[ng] - /Users/stojan/development/cordova-ionic-chat-app/node_modules/loader-runner/lib/LoaderRunner.js
[ng] - /Users/stojan/development/cordova-ionic-chat-app/node_modules/webpack/lib/NormalModule.js
[ng] - /Users/stojan/development/cordova-ionic-chat-app/node_modules/webpack/lib/NormalModuleFactory.js
[ng] - /Users/stojan/development/cordova-ionic-chat-app/node_modules/webpack/lib/Compiler.js
[ng] - /Users/stojan/development/cordova-ionic-chat-app/node_modules/webpack/lib/webpack.js
[ng] - /Users/stojan/development/cordova-ionic-chat-app/node_modules/@angular-devkit/build-webpack/src/webpack/index.js
[ng] - /Users/stojan/development/cordova-ionic-chat-app/node_modules/@angular-devkit/build-webpack/src/index.js
[ng] - /Users/stojan/development/cordova-ionic-chat-app/node_modules/@angular-devkit/build-angular/src/dev-server/index.js
[ng] - /Users/stojan/development/cordova-ionic-chat-app/node_modules/@angular/cli/node_modules/@angular-devkit/architect/src/architect-legacy.js
[ng] - /Users/stojan/development/cordova-ionic-chat-app/node_modules/@angular/cli/node_modules/@angular-devkit/architect/src/index.js
[ng] - /Users/stojan/development/cordova-ionic-chat-app/node_modules/@angular/cli/models/architect-command.js
[ng] - /Users/stojan/development/cordova-ionic-chat-app/node_modules/@angular/cli/commands/build-impl.js
[ng] - /Users/stojan/development/cordova-ionic-chat-app/node_modules/@angular/cli/node_modules/@angular-devkit/schematics/tools/export-ref.js
[ng] - /Users/stojan/development/cordova-ionic-chat-app/node_modules/@angular/cli/node_modules/@angular-devkit/schematics/tools/index.js
[ng] - /Users/stojan/development/cordova-ionic-chat-app/node_modules/@angular/cli/utilities/json-schema.js
[ng] - /Users/stojan/development/cordova-ionic-chat-app/node_modules/@angular/cli/models/command-runner.js
[ng] - /Users/stojan/development/cordova-ionic-chat-app/node_modules/@angular/cli/lib/cli/index.js
[ng] - /Users/stojan/development/cordova-ionic-chat-app/node_modules/@angular/cli/lib/init.js
[ng] - /Users/stojan/development/cordova-ionic-chat-app/node_modules/@angular/cli/bin/ng
[ng]     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
[ng]     at Function.Module._load (node:internal/modules/cjs/loader:778:27)
[ng]     at Module.require (node:internal/modules/cjs/loader:1005:19)
[ng]     at require (node:internal/modules/cjs/helpers:102:18)
[ng]     at Object.sassLoader (/Users/stojan/development/cordova-ionic-chat-app/node_modules/sass-loader/lib/loader.js:46:72)
[ng] ERROR in ./src/app/groupchat-view/groupchat-view.page.scss
[ng] Module build failed (from ./node_modules/sass-loader/lib/loader.js):
[ng] Error: Cannot find module 'node-sass'
[ng] Require stack:
[ng] - /Users/stojan/development/cordova-ionic-chat-app/node_modules/sass-loader/lib/loader.js
[ng] - /Users/stojan/development/cordova-ionic-chat-app/node_modules/loader-runner/lib/loadLoader.js
[ng] - /Users/stojan/development/cordova-ionic-chat-app/node_modules/loader-runner/lib/LoaderRunner.js
[ng] - /Users/stojan/development/cordova-ionic-chat-app/node_modules/webpack/lib/NormalModule.js
[ng] - /Users/stojan/development/cordova-ionic-chat-app/node_modules/webpack/lib/NormalModuleFactory.js
[ng] - /Users/stojan/development/cordova-ionic-chat-app/node_modules/webpack/lib/Compiler.js
[ng] - /Users/stojan/development/cordova-ionic-chat-app/node_modules/webpack/lib/webpack.js
[ng] - /Users/stojan/development/cordova-ionic-chat-app/node_modules/@angular-devkit/build-webpack/src/webpack/index.js
[ng] - /Users/stojan/development/cordova-ionic-chat-app/node_modules/@angular-devkit/build-webpack/src/index.js
[ng] - /Users/stojan/development/cordova-ionic-chat-app/node_modules/@angular-devkit/build-angular/src/dev-server/index.js
[ng] - /Users/stojan/development/cordova-ionic-chat-app/node_modules/@angular/cli/node_modules/@angular-devkit/architect/src/architect-legacy.js
[ng] - /Users/stojan/development/cordova-ionic-chat-app/node_modules/@angular/cli/node_modules/@angular-devkit/architect/src/index.js
[ng] - /Users/stojan/development/cordova-ionic-chat-app/node_modules/@angular/cli/models/architect-command.js
[ng] - /Users/stojan/development/cordova-ionic-chat-app/node_modules/@angular/cli/commands/build-impl.js
[ng] - /Users/stojan/development/cordova-ionic-chat-app/node_modules/@angular/cli/node_modules/@angular-devkit/schematics/tools/export-ref.js
[ng] - /Users/stojan/development/cordova-ionic-chat-app/node_modules/@angular/cli/node_modules/@angular-devkit/schematics/tools/index.js
[ng] - /Users/stojan/development/cordova-ionic-chat-app/node_modules/@angular/cli/utilities/json-schema.js
[ng] - /Users/stojan/development/cordova-ionic-chat-app/node_modules/@angular/cli/models/command-runner.js
[ng] - /Users/stojan/development/cordova-ionic-chat-app/node_modules/@angular/cli/lib/cli/index.js
[ng] - /Users/stojan/development/cordova-ionic-chat-app/node_modules/@angular/cli/lib/init.js
[ng] - /Users/stojan/development/cordova-ionic-chat-app/node_modules/@angular/cli/bin/ng
[ng]     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
[ng]     at Function.Module._load (node:internal/modules/cjs/loader:778:27)
[ng]     at Module.require (node:internal/modules/cjs/loader:1005:19)
[ng]     at require (node:internal/modules/cjs/helpers:102:18)
[ng]     at Object.sassLoader (/Users/stojan/development/cordova-ionic-chat-app/node_modules/sass-loader/lib/loader.js:46:72)
`

**Comment by stojankukrika** [comment]
just close without any solution...interesting :)
